config/routes.rb
Rails.application.routes.draw do
  get '/seasons', to: 'seasons#index', as: :seasons
  get '/seasons/:season_name', to: 'seasons#show', as: :season
  get '/seasons/:season_name/weeks/:week_number', to: 'weeks#show', as: :season_week
  get '/seasons/:season_name/characters/:character_id', to: 'characters#show', as: :season_character

  namespace :api do
    get :teams, to: 'teams#index'

    namespace :current_season do
      get :characters, to: 'characters#index'
      get :rando_picks, to: 'rando_picks#index'
      post :rando_picks, to: 'rando_picks#create'
      get 'weeks/:week_number/active_teams', to: 'active_teams#index'
      post :picks, to: 'picks#create'
    end
  end

  root to: 'pages#home'
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :player
  belongs_to :season

  has_many :picks, dependent: :destroy

  def score
    picks.map(&:score).sum
  end
end

app/models/current_character.rb
class CurrentCharacter
  def self.all(season)
    season.characters.map &self.method(:new)
  end

  attr_reader :character

  delegate :id, :player, :out, to: :character

  def initialize(character)
    @character = character
  end

  def player_name
    player.name
  end

  def current_picks
    character.picks.map &CurrentPick.method(:new)
  end
end

app/models/current_pick.rb
class CurrentPick
  attr_accessor :pick

  delegate :team, :week, to: :pick

  def initialize(pick)
    @pick = pick
  end

  def week_number
    week.number
  end

  def team_id
    team.id
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :home_team, class_name: 'Team'
  belongs_to :away_team, class_name: 'Team'
  belongs_to :week

  def winning_team
    if complete?
      home_score > away_score ? home_team : away_team
    end
  end

  def losing_team
    if complete?
      home_score < away_score ? home_team : away_team
    end
  end

  def delta
    if complete?
      (home_score - away_score).abs
    end
  end

  def complete?
    !!(home_score && away_score)
  end

  def teams
    [home_team, away_team].compact
  end
end

app/models/pick.rb
class Pick < ActiveRecord::Base
  belongs_to :character
  belongs_to :week
  belongs_to :team

  def correct?
    game.winning_team == team
  end

  def delta
    game.delta
  end

  def score
    PickScore.for self
  end

  def game_complete?
    game.complete?
  end

  private

  def game
    @game ||= week.game_for team
  end
end

app/models/pick_score.rb
class PickScore
  def self.for(pick)
    new(pick).score
  end

  attr_reader :pick

  def initialize(pick)
    @pick = pick
  end

  def score
    return 0 unless game_complete?
    return delta if scoring_week && character_won
    character_won ? 0 : -delta
  end

  private

  def scoring_week
    pick.week.scoring_week
  end

  def character_won
    pick.correct?
  end

  def game_complete?
    pick.game_complete?
  end

  def delta
    pick.delta
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :characters, dependent: :destroy
end

app/models/rando.rb
class Rando
  def self.wins
    RandomPick.all.select(&:correct?).count
  end

  def self.losses
    RandomPick.count - self.wins
  end

  def self.ratio
    ratio = self.wins / RandomPick.count.to_f
    sprintf( "%0.03f", ratio)
  end
end

app/models/random_pick.rb
class RandomPick < ActiveRecord::Base
  belongs_to :week
  belongs_to :team

  def correct?
    game.winning_team == team
  end

  def game
    @game ||= week.game_for team
  end
end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :weeks, dependent: :destroy
  has_many :characters, dependent: :destroy

  def self.current
    order(:id).last
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :season
  has_many :games, dependent: :destroy
  has_many :picks, dependent: :destroy
  has_one :random_pick, dependent: :destroy

  def scoring_week
    !random_pick.correct?
  end

  def game_for(team)
    games.where("home_team_id = ? OR away_team_id = ?", team.id, team.id).first
  end

  def next_week
    season.weeks.where(number: number + 1).first
  end

  def prev_week
    season.weeks.where(number: number - 1).first
  end

  def complete?
    games.all? &:complete?
  end

  def active_teams
    games.map(&:teams).flatten.map(&:id).sort
  end
end

app/controllers/api/teams_controller.rb
class Api::TeamsController < ApiController
  expose(:teams) { Team.all }
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  expose(:season, find_by: :name, id: :season_name)
  expose(:character)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  expose(:wins) { Rando.wins }
  expose(:losses) { Rando.losses }
  expose(:ratio) { Rando.ratio }
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  expose(:seasons) { Season.all }
  expose(:season, find_by: :name, id: :season_name)
  expose(:weeks) { season.weeks }
  expose(:characters) { season.characters.sort_by(&:score).reverse }
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  expose(:season, find_by: :name, id: :season_name)
  expose(:week) { season.weeks.find_by number: params[:week_number] }
  expose(:games) { week.games.order :played_at }
  expose(:picks) { week.picks.sort_by(&:score).reverse }
  expose(:pick_presenter) { PickOfTheWeekPresenter.new games }
  expose(:next_week) { week.next_week }
  expose(:prev_week) { week.prev_week }
  expose(:rando_pick) { week.random_pick }
end

app/helpers/application_helper.rb
module ApplicationHelper
  def rando_result(random_pick)
    game = random_pick.game

    if random_pick.correct?
      "No points this week - Rando's pick was the #{game.winning_team.name}, who beat the #{game.losing_team.name}."
    else
      "Points this week - Rando's pick was the #{game.losing_team.name}, who lost to the #{game.winning_team.name}."
    end
  end

  def pick_result(pick)
    return "-" unless pick.game_complete?
    pick.correct? ? "Won" : "Lost"
  end

  def character_status(character)
    character.out ? "Out" : "In"
  end
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title The Rando Calrissian Football Pool
  = stylesheet_link_tag 'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags

%body
  %header
    %h1 The Rando Calrissian Football Pool
  %div#page= yield

app/views/pages/home.html.haml
%p= link_to "Seasons", seasons_path

%aside
  %h2 Rando's Record
  %p #{wins}-#{losses} (#{ratio})

%article
  :markdown
    ## Rules

    Rando Calrissian, known throughout the galaxy for his habit of random
    gambling, invites you to join his modified NFL survivor pool. Read on for
    the rules.

    ## Picks

    Each week Rando will secretly pick an NFL team at random. You pick one as
    well. After that week's games have been played, each player's pick is scored
    and one of four things could happen:

    1. Your team wins and Rando's team loses: congrats, you've just earned some
       points (more on this in a bit) and you're through to the next week.
    2. Your team wins and so does Rando's team: no points, but you're still
       through to the next week.
    3. Your team loses and so does Rando's team: you get through to the next
       week, but you lose some points.
    4. Your team loses, but Rando's wins: tough luck, you're out of the pool
       and you lose some points.

    You have until midnight each Wednesday to email in your pick. Rando's choice
    is revealed every Thursday morning. If you do not send in a pick, then you
    automatically get the team that is playing Rando's pick.

    ## Points

    You start with zero points and then outcomes 1, 3 and 4 above add or
    subtract from that amount. Points are based on the delta of the scores of
    your team and their opponent. Say the Bears beat the Packers by 14. If you
    took the Bears and get outcome 1, then you just picked up 14 points. If you
    took the Packers and get outcome 3, then you lose 14 points. Same goes for
    outcome 4 - you'd lose 14 points.

    ## Entry Fees

    The fee to enter the pool is $10 per player, payable via PayPal to
    jon.allured@gmail.com.

    ## Aliases

    One thing Rando prides himself on is taking care of the needs of his
    clients.  He understands that his clientele are a certain type of person
    and that privacy is very important to them. To this end, aliases are
    assigned to each player. When picks are announced, no one knows who has
    picked which team.

    ## The Jar Jar Penalty

    After your rookie season, you are subject to the Jar Jar Penalty. The last
    veteran player to send their entry fee will get Jar Jar as their alias.
    Turn that money in!

    ## Weekly Emails

    Thursday morning the picks email goes out where you can see which teams have
    been picked - this is the email where you find out Rando's pick.

    Tuesday morning the results email goes out that recaps the week and updates
    the standings with how each player did.

    ## Re-entry

    Once per season, a player that was knocked out may pay to re-enter the pool
    the following week. The fee for re-entry is based on the week they want to
    re-enter. Say a player is knocked out in the first week and wants to pay to
    re-enter week two. That player would have to pay $10 * 2 or $20. Say a player
    is knocked out in week 9 and wants to re-enter week 10, that player would
    have to pay $10 * 10 or $100.

    Re-entry is expensive, but allows players that get screwed early in the
    season to get back in. It also allows players doing well at the end of the
    season to keep going with a great score. In both cases, the pot grows and it
    just means more money for the winners.

    ## End of the Season

    Players are ranked by points and at the end of the season, the top three
    players get paid. Yes, you can have a negative amount of points.

    It's possible to be knocked out and still place in the rankings - getting
    knocked out just means you aren't able to score any further points.

    An end of season summary email goes out with the final standings and the
    winners are paid out.

    ## Payouts

    At the end of the season, the top three players are paid out in a 65-25-10
    split of the pot.